### ISSUE TITLE
model-based pileup %methylation is independent of the number of reads

### ISSUE THREAD

**Issue by rhallPB** [PacificBiosciences/pb-CpG-tools#1]
Carryover issue:

Because of the model-based pileup, the % methylation is no longer strictly correlated with the number of methylated reads. For example, the first line below has 4x coverage but not 75% or 100% of methylation (having 3 or 4 reads methylated). Some downstream processing methods like MethylSeekR use the number of methylated and unmethylated read counts to find UMRs. Is it possible to also output this information or it will be confusing? Or maybe outputting both frequency-based and model-based % methylation.

B73_chr1 5295 5296 94.5 merged Total 4

**Comment by dportik** [comment]
Features added in in https://github.com/PacificBiosciences/pb-CpG-tools/pull/2
