### ISSUE TITLE
FASTA and BED file contig names do not match error

### ISSUE THREAD

**Issue by rashidalabri** [PacificBiosciences/pb-CpG-tools#10]
Hi @dportik,
I ran the tool on a single chromosome and was able to run the analysis for the most part. However, when the tool begins generating the bigWig file, it reports an error:

```
  Traceback (most recent call last):
    File "aligned_bam_to_cpg_scores.py", line 981, in <module>
      main()
    File "aligned_bam_to_cpg_scores.py", line 976, in main
      convert_bed_to_bigwig(bed_files, args.fasta, args.pileup_mode)
    File "aligned_bam_to_cpg_scores.py", line 949, in convert_bed_to_bigwig
      write_bigwig_from_df(df, header, outname)
    File "aligned_bam_to_cpg_scores.py", line 911, in write_bigwig_from_df
      raise ValueError("No reference contig names match between bed file and reference fasta!")
  ValueError: No reference contig names match between bed file and reference fasta!
```

I manually checked the generated .bed files and the reference FASTA and they both match in terms of contig names. And in this case, there is a "4" contig in both files for chromosome 4.

**Comment by dportik** [comment]
Hi @rashidalabri,
Would you be able to attach the log file from the run? I am traveling for the remainder of this week but will take a look once back.

**Comment by dportik** [comment]
@rashidalabri is there any update on this? If not I will close the issue.
