### ISSUE TITLE
cg_sites_dict UnboundLocalError

### ISSUE THREAD

**Issue by sunkelb** [PacificBiosciences/pb-CpG-tools#20]
Hi,

I've run this tool with the public HG002 data provided by PacBio with no issue. When I tested with an aligned bam of my own, I got the errors in the attached log. I referenced the same genome fasta in each instance. Could you help me understand the issue?

Thanks!
[CpG_Test.o3030880.txt](https://github.com/PacificBiosciences/pb-CpG-tools/files/8949203/CpG_Test.o3030880.txt)

**Comment by dportik** [comment]
Hello @sunkelb ,
It appears you are using an outdated version of this script. The code referenced in the error message no longer exists in the current version. Please download the current version and re-run the script.

**Comment by sunkelb** [comment]
Thank you, @dportik !

I ran again with the update and none of the sequences were found in the ref fasta. Has this issue been observed by others?
