### ISSUE TITLE
question for output

### ISSUE THREAD

**Issue by hmyh1202** [PacificBiosciences/pb-CpG-tools#22]
Hello:

For -p count, four additional columns are present:

    modified site count
    unmodified site count
    avg mod score
    avg unmod score

Dose "The modified site count" is methylated（methylation level>50%） CpG number in that position for all HiFi reads aligned?

How I caculate the methylation level of for a CpG site and for a special genomic region ?  could I just use modified site count/(modified site count+unmodified site count)  ?

The best ！

Thank you !

**Comment by hmyh1202** [comment]
Thank you !  I  will  use -p model re-run my PB dataset.

So, the column 4 of  modification probability  be equal to the methylation level ?

If  I want to caculate the methylation level  value  for a special gene, if the mean modification probability of all CpGs for that gene ? 


Thank you!

**Comment by dportik** [comment]
@hmyh1202 

```
So, the column 4 of modification probability be equal to the methylation level ?
```
Yes.

```
If I want to caculate the methylation level value for a special gene, if the mean modification probability of all CpGs for that gene ?
```
There are many approaches to determining the methylation status of a CpG island or gene region. We do not currently have a recommendation for this, but your approach seems reasonable.

**Comment by hmyh1202** [comment]
When I use parameter of -c 1 for 1x coverage output, the tool only 4x coverage CpGs？

**Comment by dportik** [comment]
Yes 4x is the minimum in order to run the model for a given site. You can use `count` mode for 1x coverage, but in general 1x coverage is not informative for analysis.
