### ISSUE TITLE
What is the different between pb model and HK model 

### ISSUE THREAD

**Issue by hmyh1202** [PacificBiosciences/pb-CpG-tools#30]
Hello:
      
     The paper provided a HK model for detect 5mC in PacBio HiFi reads ( PNAS.Genome-wide detection of cytosine methylation by single molecule real-time sequencing ), and what is the difference between your model and the HK model, and if you can do some comparision for that model ?  Thank you! 

The best !

**Comment by ctsa** [comment]
Hi @hmyh1202, The HK model is for 5mC basemod calling on individual reads, this tool is for calling 5mC sites from a read pileup.
