### ISSUE TITLE
DtypeWarning: Columns (8) have mixed types

### ISSUE THREAD

**Issue by elcortegano** [PacificBiosciences/pb-CpG-tools#33]
I'm running `aligned_bam_to_cpg_scores.py` on count mode as follows:

    python3 aligned_bam_to_cpg_scores.py -b sample.5mc.pbmm2.bam -f reference.fa -o sample -p count -t 32

Just after the message "Writing bigwig files." is printed, I get the following warning:

> /path/aligned_bam_to_cpg_scores.py:1047: DtypeWarning: Columns (8) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(bed, sep='\t', header=None,

This is printed a couple of times, and the program ends. How concerning is this warning? what could be causing it? thanks

**Comment by ctsa** [comment]
Hi @elcortegano,

I don't believe this issue has been reproduced by our team, but there have been various conda/package issues causing site-specific behaviors. For this reason the python method has just been updated with a new compiled binary v2.1.0 release today to help better manage these:

https://github.com/PacificBiosciences/pb-CpG-tools/releases/latest

If you're still interested, can you give this a try instead?

**Comment by ctsa** [comment]
Closing as no longer applicable. Please open a new issue if you're having any trouble with v2.
