### ISSUE TITLE
Models suitable for plants?

### ISSUE THREAD

**Issue by hrpelg** [PacificBiosciences/pb-CpG-tools#36]
Hi, 

I have just run the count mode and I would like to run a model now but I wonder which one would be good for plants. Or should I use other tools for these purpose? Do you know any? I am very new on methylation calling with Hifi data

From the bed file out of the count mode I should consider the methylation sites the higher the column 2 the better (more probable methylation site) what is a good cut off for filtering sporious calls? the only filtering I did was with coverage min 10

Many thanks

E

**Comment by dportik** [comment]
Hi @hrpelg ,
We strongly recommend using `aligned_bam_to_cpg_scores.py` with `-p model`. The model used here is not specific to any organism and is just a minor correction to the distribution of probability scores. 

You may not need any additional filtering after using `-p model`, especially if you are setting the minimum coverage to 10 or greater.

**Comment by ctsa** [comment]
Closing as inactive.
