### ISSUE TITLE
strand specific extraction

### ISSUE THREAD

**Issue by xiaoyunguo** [PacificBiosciences/pb-CpG-tools#37]
Hi, 

I want to do strand specific methylation extraction, I wonder if there is a way to do it? say setting the haplotype tag in some way? 

Thanks

Xiaoyun

**Comment by ctsa** [comment]
Hi Xiaoyun, Do you mean the read's alignment orientation? Although it is not supported, you are right that you could have the output arbitrarily partitioned using the haplotype tag, just add `HP` aux tag values of `1` and `2` two the two sets of reads for which you would like separate tracks.

**Comment by ctsa** [comment]
Closing as answered, please reopen if needed.
