### ISSUE TITLE
Can I use CpG tools if I have other basemods in the file

### ISSUE THREAD

**Issue by mrvollger** [PacificBiosciences/pb-CpG-tools#48]
Hi @ctsa,

I think the answer is going to be no based on a phrase in the docs but can I use CpG tools if I have other basemods in addition to CpG in the MM and ML tags? 

Thanks!
Mitchell

**Comment by ctsa** [comment]
Hi @mrvollge - It's possible we could support this if we had some way to verify correctness, and parse the two modifications serially instead of the multi-modification format also described in the spec. I'll followup with you for details.

**Comment by ctsa** [comment]
I checked the parser code tests and completed a test on a bam file with other basemods besides 5mC. It looks like this capability is already supported and works correctly. I'll update the README to reflect this. Please reopen this ticket if you run into problems.
