### ISSUE TITLE
Availability of jasmine

### ISSUE THREAD

**Issue by PengNi** [PacificBiosciences/pb-CpG-tools#50]
Hi, dear developers,

I notice that in the README you have replaced primrose by jasmine. Is jasmine the new PacBio tool for 5mC detection? If so, when will it be available for us? Are there new features in jasmine? I just can't wait to try it!

Best,
Peng

**Comment by ctsa** [comment]
Thanks for your interest Peng, and sorry for any confusion. I've updated the readme to reflect available tools.
