### ISSUE TITLE
Primrose unavailable

### ISSUE THREAD

**Issue by scorreard** [PacificBiosciences/pb-CpG-tools#51]
Hi team,

I used to use the pipeline with primrose.
Unfortunately, it seems that primrose 'disappeared'? 
It is no longer on GitHub, conda, or even singularity.

Could you let me know what happened and what is the way forward to extract the 5mC base modification values from the MM and ML auxiliary tags which encode base modifications and confidence values?

Thanks,
Best,

Solenne

**Comment by ctsa** [comment]
Hi Solenne,

There will be a new 5mC caller release in a few weeks. If needed you can currently run 5mC calling through SMRTLink:

https://www.pacb.com/support/software-downloads/

**Comment by scorreard** [comment]
Thanks! Looking forward to it!
