### ISSUE TITLE
Suggestions for indicating methylation regions on circos plots?

### ISSUE THREAD

**Issue by Wenwen012345** [PacificBiosciences/pb-CpG-tools#53]
Hello! @jkaralius @ctsa 

The pb-CpG-tools is a very good tool and is suitable for us to HIFI sequence the genome of our species. Now I would like to draw a Circos map with CpG methylation regions and would like to hear your advice. The tool I am using is TBtools, Acvanced circos function (https://onlinelibrary.wiley.com/doi/pdfdirect/10.1002/imt2.35). I noticed that pb-cpg-tools outputs a file in .bed format. In my case it is "out.aligned.pcg.bam.combined.bed", "out.aligned.pcg.bam.combined.bw" respectively. This is the file I want to use for indicating genomic methylation. I just want to ask: 
1. Since the format that TBtools (and possibly other circos software) is suitable for is gff3 etc., how can I convert the bed file to a file format that is suitable for circos images? 
2. After conversion, if I need to annotate the circos map with CpG methylation density information (or probability), what is the unit fragment length that you suggest? For example, when labelling gene density, 100,000 bp would be used as the unit fragment length; 
3. Do you recommend labelling the "probability" or "density" of CpG methylation(I understand this to mean the number of methylated bases per unit length ) on the circos map? 
4. Is there any similar reference?

Thank you for your help and look forward to your answer!
BEST！

**Comment by ctsa** [comment]
Thanks @Wenwen012345 , these are great questions for downstream analysis of the pb-CpG-tools output, but a bit out of scope for tool improvement. So long as the the bed output contains the information necessary to be converted to other common formats we're unlikely to output another format like gff3 directly. The following paper might be used as one example of a circos figure with a methylation track (from bisulfide seq in this instance):

https://www.researchgate.net/publication/350515023_Changes_in_DNA_Methylation_in_Arabidopsis_thaliana_Plants_Exposed_Over_Multiple_Generations_to_Gamma_Radiation
