### ISSUE TITLE
the question about hap1 and hap2

### ISSUE THREAD

**Issue by crazysummerW** [PacificBiosciences/pb-CpG-tools#57]
Hello! 
Thank you very much for developing such excellent analysis software. 
I have obtained the CpG analysis results of hap1 and hap2 (WGS). Now I want to analyze the DMR (Differentially Methylated Region) between hap1 and hap2. The amount of WGS data is too large for me to visually identify candidate regions effectively. 
However, I have not found any suitable software for PacBio data. Most of them are applicable to BS-Seq data. Could you please recommend any appropriate tools or analysis methods?

Looking forward to your reply.
Thanks.

**Comment by ctsa** [comment]
Thanks @crazysummerW ,

@holtjma has recently released a tool, MethBat, which may help. It can process pb-CpG-tools output to classify the state of CpG Islands and identify anomalous methylation states relative to a background cohort. You can find more details here:

https://github.com/PacificBiosciences/MethBat

**Comment by ctsa** [comment]
Closing as answered.
