### ISSUE TITLE
need clarifications on the workflow

### ISSUE THREAD

**Issue by splaisan** [PacificBiosciences/pb-CpG-tools#58]
Dear all,

I am not sure I understood all the details of this pipeline.
I have HiFi reads from a SequelIIe from a run with kinetics ON
Is it correct that I need to run:

* jasmine on my original SMRT-LINK HiFi reads with kinetic info (m123456e_230922_123124.hifi_reads.bam )
* pbmm2 align (with --sort) of the resulting jasmine BAM reads against the reference genome
* aligned_bam_to_cpg_scores on the pbmm2 sorted BAM mappings

Please correct me if I misunderstood!

Thanks in advance 
Stephane

**Comment by ctsa** [comment]
Hi @splaisan - Sorry for the delay, yes that is the correct workflow starting from a bam file with kinetics.
