### ISSUE TITLE
Add to bioconda

### ISSUE THREAD

**Issue by mobilegenome** [PacificBiosciences/pb-CpG-tools#59]
If I saw correctly, this repository is not (yet?) available via bioconda or under the umbrella of the [pbbioconda](https://github.com/PacificBiosciences/pbbioconda) repository. Having the possibilty to install it via conda would make using it in workflows much easier. Are there any plans to add it? 

Thanks, 
Fritjof

**Comment by ctsa** [comment]
Thanks for the input @mobilegenome. While there is not a concrete plan to add it right now, this is a good item to consider. One issue with bioconda distribution is making sure we can provide reliable access to the recommended tflite model file. I think we have a few options, even the possibility of building it into the binary, so we'll continue to look into this.
