### ISSUE TITLE
Tools for mapping methylation and expression relationships

### ISSUE THREAD

**Issue by Wenwen012345** [PacificBiosciences/pb-CpG-tools#62]
Hello author! @ctsa @jkaralius 

I now want to map the relationship between methylation and expression around genes and within them. What tools can be used to achieve this? Specifically,  the gene expression scores are expressed in sections, and then the methylation levels of these differently expressed genes are segmented on a line graph. It's similar to the picture below.

![image](https://github.com/PacificBiosciences/pb-CpG-tools/assets/63379795/d6a50d10-45c2-4121-92ae-64e77263baf3)

**Comment by lanyunxin** [comment]
https://github.com/GuoliangLi-HZAU/BatMeth2

**Comment by lanyunxin** [comment]
https://github.com/GuoliangLi-HZAU/BatMeth2

**Comment by Wenwen012345** [comment]
> https://github.com/GuoliangLi-HZAU/BatMeth2

Hello, thank you for your reply.  I have tried this tool before, but there were formatting issues.  I wrote a script myself to handle this problem.

**Comment by lanyunxin** [comment]
> > https://github.com/GuoliangLi-HZAU/BatMeth2
> 
> Hello, thank you for your reply. I have tried this tool before, but there were formatting issues. I wrote a script myself to handle this problem.

Did you draw this graph with the results of pb-CpG-tools? If possible, would you like to share with me how to draw it?

**Comment by Wenwen012345** [comment]
Hello. I am quite busy these days. But that was achieved by the python script and drew by R. I may upload that relevant script someday.

---- Replied Message ----
| From | ***@***.***> |
| Date | 11/06/2023 14:24 |
| To | PacificBiosciences/pb-CpG-tools ***@***.***> |
| Cc | Wenwen ***@***.***>,
Author ***@***.***> |
| Subject | Re: [PacificBiosciences/pb-CpG-tools] Tools for mapping methylation and expression relationships (Issue #62) |

https://github.com/GuoliangLi-HZAU/BatMeth2

Hello, thank you for your reply. I have tried this tool before, but there were formatting issues. I wrote a script myself to handle this problem.

Did you draw this graph with the results of pb-CpG-tools? If possible, would you like to share with me how to draw it?
