### ISSUE TITLE
Empty BED file

### ISSUE THREAD

**Issue by roybarkan2020** [PacificBiosciences/pb-CpG-tools#63]
Hi !

I've used minimap2 to map my HiFi reads (with MM and ML tags) with my reference genome. 
$ minimap2 -ax map-pb -Y scaffolds_final.fa HiFi.fastq > aln_CpG.sam
# I've converted the sam alignment file to a sorted, indexed bam file using samtools:
$ samtools view -Sb -o aln_CpG.bam aln_CpG.sam
$ samtools sort -O bam -o sorted_aln_CpG.bam aln_CpG.bam
$samtools index sorted_aln_CpG.bam

When running pb-CpG-tools using the indexed bam file, I get a BW file and an empty BED file. I am unsure if I am "losing" the MM and ML tags somewhere in the process... I have used the "soft clipping" option for minimap.

Any ideas about what might be the issue?

Thanks!

**Comment by Eva-Green** [comment]
Hello，I also encountered the same problem, please how to solve it in the end

**Comment by roybarkan2020** [comment]
Eva, start by running this code (using your aligned minimap output file) to see if your BAM file includes the methylation tags:

samtools view <aln_CpG.bam> | head -n 1 | tr '\t' '\n' | less -S

**Comment by Eva-Green** [comment]
> Eva, start by running this code (using your aligned minimap output file) to see if your BAM file includes the methylation tags:
> 
> samtools view <aln_CpG.bam> | head -n 1 | tr '\t' '\n' | less -S

Thank you for your answer, I don't really have a methylation tags in my bam file. My last step was 【pbmm2 align EIL08.v1.chr.fasta EIL08.merge.ccs.fasta.gz EIL08.pbmm2.bam --sort -J 100 --rg '@RG\tID:EIL08\tSM:EIL08'】Is this the reason for this? Best wishes

**Comment by roybarkan2020** [comment]
Not sure. 
Are you sure your sequencing provider included the methylation calling in your fasta file?

**Comment by Eva-Green** [comment]
> Not sure. Are you sure your sequencing provider included the methylation calling in your fasta file?

It was ok but now it needs to be checked again, thanks for your help and good luck
