### ISSUE TITLE
About haplotype output

### ISSUE THREAD

**Issue by woshiakai5525** [PacificBiosciences/pb-CpG-tools#64]
pb-CpG-tools is a powerful and useful tool to me. But I can't output hap.bed and hap.bw files. I will show you my command line as below.

aligned_bam_to_cpg_scores --bam haplotagged.bam --model pileup_calling_model.v1.tflite --output-prefix cpg_output --threads 24 --hap-tag HP

The haplotagged.bam is phased by whatshap, and I have confirmed the hap tag in the bam file as "HP:i:1" or "HP:i:2". The output files are only cpg_output.combined.bed  and cpg_output.combined.bw but hap1 and hap2 files. The version is aligned_bam_to_cpg_scores 2.3.1.

Could you correct my mistake or give me some advice? Thank you.

**Comment by ctsa** [comment]
Thanks, this is unexpected, especially since whatshap output is tested.

1. Does aligned_bam_to_cpg_scores complete and exit 0 when this happens?
2. Do the combined bed/bw tracks contain the information you expect?
3. Can you share a few SAM lines of the bam input as examples?

**Comment by woshiakai5525** [comment]
> Thanks, this is unexpected, especially since whatshap output is tested.
> 
> 1. Does aligned_bam_to_cpg_scores complete and exit 0 when this happens?
> 2. Do the combined bed/bw tracks contain the information you expect?
> 3. Can you share a few SAM lines of the bam input as examples?

Thank you for your quick response. I am sorry I made a mistake in my bam file. I have already corrected my mistake and outputted the hap1 and hap2 bw/bed files. Sorry for the inconvenience and please close this issue.

**Comment by ctsa** [comment]
No problem, good to hear things are working.
