### ISSUE TITLE
cannot get 5mc probability Revio platform 

### ISSUE THREAD

**Issue by Duyh814** [PacificBiosciences/pb-CpG-tools#65]
Hey i 'm now trying to call 5mc probability from Pacbio revio ccs.bam, but i failed. i find the hifi-kinetic signal in revio ccs.bam, but i can not use pbmm2 map the methyaltion signal  to reference genome, which is different from pacbio seqII platform. Is there anyway to call the 5mc probability from pacbio revio platform

**Comment by ctsa** [comment]
Hi @Duyh814, You can use Jasmine (https://github.com/PacificBiosciences/jasmine) to first process the kinetic signal into 5mC probabilities, then map with pbmm2. After mapping pb-CpG-tools can be used to generate 5mC pileup tracks.

**Comment by Duyh814** [comment]
> Hi @Duyh814, You can use Jasmine (https://github.com/PacificBiosciences/jasmine) to first process the kinetic signal into 5mC probabilities, then map with pbmm2. After mapping pb-CpG-tools can be used to generate 5mC pileup tracks.

Thank you, I appreciate it.

**Comment by Duyh814** [comment]
@ctsa
Hi ，Is this software a replacement for primrose? I‘m not sure if their having same function

**Comment by ctsa** [comment]
Yes jasmine is the replacement for primrose.
