### ISSUE TITLE
# Questions about jasmine

### ISSUE THREAD

**Issue by xiangpingyu** [PacificBiosciences/pb-CpG-tools#66]
Dear developers,

I am currently exploring the capabilities of your tool, Jasmine, particularly in the context of epigenetic modification detection using high-fidelity (HiFi) reads. My interest lies primarily in the detection of 5mC modifications through analysis with hifi_read.bam files. A question that arises in my research is whether Jasmine is capable of predicting 5mC modifications without the need for reference information. Is the tool designed to autonomously improve the detection based on the context dependence of polymerase kinetic signals?

Additionally, given the tool’s existing framework for 5mC detection, I am curious about its applicability and effectiveness in predicting m6A modifications. Are there any specific considerations or adjustments required to utilize Jasmine for m6A detection?

I appreciate your time and effort in developing such a versatile tool and look forward to your insights on these queries.

Best,
Sophia

**Comment by ctsa** [comment]
Hi Sophia, This repo is setup for issues with pb-CpG-tools, for future reference Jasmine questions can be posted to:

https://github.com/PacificBiosciences/pbbioconda/issues

I can add some brief comments here before closing -- Jasmine doesn't require mapped input so doesn't need reference information. Jasmine doesn't support 6mA calling, however there are independent community tools such as fibertools https://github.com/fiberseq/fibertools-rs with related capabilities.
