### ISSUE TITLE
Criterion for error: Read sequence is too short for MM tag offsets in bam record

### ISSUE THREAD

**Issue by aewrwdw** [PacificBiosciences/pb-CpG-tools#67]
Dear developer! @ctsa I get five bam libraries in the same individual, but one of them has this error. To determine and resolve this error, I want to know the criterion for determining this error, i.e. how long the shortest read length is to be recognized by MMtag. Thank you so much!
![图片](https://github.com/PacificBiosciences/pb-CpG-tools/assets/107688124/736a99d2-b14d-4dc3-b961-712acf08ec9b)

**Comment by ctsa** [comment]
Hi @aewrwdw, This message often indicates that the read length has been modified without making the corresponding updates required of the BAM methylation tags (MM & ML). This might be a read mapper creating supplementary alignments using hard clipping (such as using the default minimap2 settings), or some type of adaptor trimming logic. For the BAM file in question, do you know of any such read-length altering operation?
