### ISSUE TITLE
 modsites-mode

### ISSUE THREAD

**Issue by wittney-m** [PacificBiosciences/pb-CpG-tools#68]
I ran this code to use the modsites-mode

aligned_bam_to_cpg_scores \
  --bam ${f}haplotagged.bam \
  --threads 8 \
  --modsites-mode reference \
 --ref /home/wdmays/coccolith_datasets/reference_genomes/Emihu2data/Emihu2_haploid_genome.fasta \

I am receiving this error: 
command-line setting: The 'model' pileup mode has been selected without specifying a model file. 

The only model I see in the model folder is for the pileup mode. Is the modsites-mode ready to run? If not, what is the alternative?

**Comment by ctsa** [comment]
The default pileup mode is 'model', which requires access to the pileup model as noted in the error, you can add something similar to the following to your command line to address this:
 
```
  --model /path/to/pb-cpg-tools/models/pileup_calling_model.v1.tflite
```

**Comment by wittney-m** [comment]
I would like to use the --modsites-mode. Would I still use the default model? I am essentially attempting to get the input regions of interest from this tool for methbat. This requires a cpg island file from the reference.  Will this be produced from the --modsites-mode option?

**Comment by ctsa** [comment]
A good place to pull CpG island tracks is directly off of the UCSC browser tables. pb-CpG-tools is a pileup utility to summarize methylation results at a site level from mapped reads, and won't create ROI or CpG island tracks.
