### ISSUE TITLE
modification probability vs discretized modification probability

### ISSUE THREAD

**Issue by Jinyulin515** [PacificBiosciences/pb-CpG-tools#69]
Hi, 

The output of pb-CpG-tools includes modification probability (column 4) and discretized modification probability (column 9) for each CpG site. I am wondering how should I consider using such information to calculate the average methylation level for each sample? How different they are in terms of representing real methylation rate per site?

**Comment by MJoseMo** [comment]
Hi @Jinyulin515 I was wondering if you had solved your question.

**Comment by ctsa** [comment]
It would make sense to prefer the modification probability as the primary output in all cases. The discretized modification probability is provided only for toolchains that require a discrete count interface to the modification probability model.
