### ISSUE TITLE
strand information on the output bed file

### ISSUE THREAD

**Issue by hrrsjeong** [PacificBiosciences/pb-CpG-tools#7]
Thanks for your effort in making this great tool! I checked the output from pb-CpG-tools and found that there's no strand information. Does the program merge the information from both strands and use the genomic coordinate of the positive strand?

**Comment by rhallPB** [comment]
The data is not stranded, i.e. the direction of a HiFi read is arbitrary and we detect symmetric CpG. Therefore we merge the stands in the pileup to increase the signal. Yes, coordinates are reported on the positive strand.
