### ISSUE TITLE
pileup for CHG and CHH contexts

### ISSUE THREAD

**Issue by jkh00** [PacificBiosciences/pb-CpG-tools#71]
Hi, 

As the title suggests, I'm wondering if it is possible to pileup methylation score for CHG and CHH contexts using this tool? 

If not, perhaps you would have some recommendations for me? I am new to the PacBio methylation community and I'm struggling to find tools dedicated to extract methylation scores of cytosines beyond the CpG context from PacBio reads. 

Many thanks in advance!

**Comment by ctsa** [comment]
pb-CpG-tools currently provides support for 5mC calls in the CpG context only.
