### ISSUE TITLE
What is the diffrence between Jasmine and  pb-CpG tools?  

### ISSUE THREAD

**Issue by aindap** [PacificBiosciences/pb-CpG-tools#72]
Hi PacBio - I'm still new to HiFi secondary analysis. I'm a little confused between the output of [Jasmine](https://github.com/PacificBiosciences/jasmine) and what pb-CpG-tools is doing. I had a pbmm2  derived BAM I pulled from  [here](https://downloads.pacbcloud.com/public/revio/2022Q4/HG002-rep1/analysis/) and the BAM file had the MM and ML tags required for pb-CpG tools. Is Jasmine doing the same thing? What exactly is the difference in the results they are returning?

**Comment by ctsa** [comment]
pb-CpG-tools is used to summarize methylation at the site level.

- When given an (un)mapped BAM file containing kinetics information, Jasmine adds read-level methylation calls (MM/ML tags).
- When given a mapped BAM file containing methylation calls (MM/ML tags), pb-CpG-tools provides site-level methylation as separate BED/BigWig outputs.

**Comment by indapa** [comment]
Thanks for the explanation @ctsa. I did notice the the HiFi WGS [workflow](https://github.com/PacificBiosciences/HiFi-human-WGS-WDL/blob/main/workflows/sample_analysis/sample_analysis.wdl)  calls pb-CpG-tools to generate the bigWig/BED output with the site level methylation probabilities, which is what I need for my downstream analysis. 

Does pbmm2 add the MM/ML tags as well when given an unmapped  BAM file with kinetics information? I didn't see Jasmine being used in the WGS WDL workflow.

**Comment by ctsa** [comment]
The most common scenario is for the methylation calling to have already been run upstream as part of SMRT Link. Jasmine can only be used if you requested BAM output with kinetics tags.
