### ISSUE TITLE
primrose need  HiFi kinetics 

### ISSUE THREAD

**Issue by hmyh1202** [PacificBiosciences/pb-CpG-tools#8]
I have download your public CCS dataset of https://downloads.pacbcloud.com/public/dataset/HG002-CpG-methylation-202202/, 

and got error as below :

primrose -j 1 ccs.bam ccs.kinetics.bam --log-level DEBUG --keep-kinetics
| 20220510 07:25:44.268 | INFO | Reads      : 0
| 20220510 07:25:44.268 | INFO | Yield      : 0 Bases
| 20220510 07:25:44.268 | INFO | Throughput : 0/min
| 20220510 07:25:44.565 | FATAL | primrose ERROR: Missing HiFi kinetics

I noticed that CCS step that recorded in the bam file is ccs 3cb15684-e46a-4752-b510-603c6cc4e018.subreadset.xml out.consensusreadset.xml --log-level INFO --chunk 1/96 --all --all-kinetics --subread-fallback --minLength 10 --maxLength 50000 --minPasses 0 --minSnr 2.5 --minPredictedAccuracy 0.0 --alarms alarms.json --task-report task-report.json --report-json ccs_processing.report.json --zmw-metrics-json ccs_zmws.json.gz -j 8

so your CCS code not used the hifi kinetics but  all kinetics

So, can you update the latest CCS file that containing hifi  tag ? 

Thank you!

**Comment by dportik** [comment]
The BAM files on the download page were previously run through `primrose` and already contain the `MM` and `ML` tags for 5mC. Attempting to run `primrose` again on these BAM files would cause the error described.
